spring:
  #注册服务
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tMT9VUtuZKLMp4bPQSh
      secret-key: MjLeoSkVVzJsYTfd056y2KEfbvspd1
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: beastmail
  #服务名字
  application:
    name: beastmail-third-party
server:
  port: 15000



