


spring:
  cloud:
    gateway:
      routes:
        - id: payment_routh   #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: https://www.baidu.com          #匹配后提供服务的路由地址
          predicates:
            - Query=url,baidu         # 断言，路径相匹配的进行路由

        - id: payment_routh2   #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: https://fanyi.baidu.com/         #匹配后提供服务的路由地址
          predicates:
            - Query=url,fanyi       # 断言，路径相匹配的进行路由